spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost/FreightsDB
    username: postgres
    password: Lalibertad98
    
server:
   port: 8030